//! SH-316: the outcome receipt — when this store last scanned a project's
//! commits, and what `story hooks install` may say about it.
//!
//! # The gap this closes, and the one it does not
//!
//! SH-313 made `story hooks install` write where git actually looks and report
//! what git will run. Every statement it prints is true when printed, and none
//! stays true: the directory it wrote into can be regenerated by husky, swept by
//! `git clean -fd`, or abandoned when `core.hooksPath` is re-pointed, and the
//! install report was correct at the time in every one of those. That is SH-306's
//! doctrine displaced in *time* — an install-time statement is not evidence of
//! commit-time execution.
//!
//! The closure is not a better install-time check; SH-313's council rejected all
//! three of those on record. It is an **outcome receipt**: do not ask whether the
//! gate is installed, ask whether it left evidence. `story commit-sync` records
//! that it ran, and `hooks install` on a re-run compares that instant against
//! git's own log.
//!
//! # What the receipt attests, stated once so no test drifts from it
//!
//! **This store scanned this project's commits at an instant.** Not that a hook
//! ran, not that a hook is installed, not where one was installed to. The
//! difference is what makes a stored record admissible here at all after the
//! state file SH-313 rejected: that file asserted a proposition about the
//! filesystem, which the filesystem could silently falsify while the record went
//! on stating it confidently. This one asserts a past event nothing can
//! un-happen, and the sentence storyhook prints is re-derived from git at check
//! time — so every disagreement between the record and the disk resolves to
//! silence rather than to a claim.
//!
//! Which is why so much of this file asserts **silence**. Four ways a genuinely
//! dark hook still reads as healthy are pinned here rather than left to be
//! discovered: a sync from somewhere else (the Claude Code plugin's own
//! `post-git.sh`, or a user's hands), the window hole, backdated committer
//! dates, and a second checkout of one project. Each is a named limit of the
//! design, and a test that asserts the limit is what stops a later reader
//! mistaking it for a bug and "fixing" it into a false alarm.

use std::path::Path;
use std::process::Command;

use storyhook::store::{ProjectId, ReadOps, SqliteStore, Store};
use storyhook_test_support::{Project, TestEnv};

/// Runs `git <args>` in `cwd` under the fixture's environment, asserting
/// success.
///
/// The environment is the load-bearing part, exactly as in
/// `tests/hook_execution.rs`: a hook runs `story` by name, and with the ambient
/// `PATH` that is whatever the developer has installed, pointed at whatever
/// store that build defaults to.
fn git(env: &TestEnv, cwd: &Path, args: &[&str]) -> String {
    let mut command = Command::new("git");
    command.current_dir(cwd);
    env.apply(&mut command);
    command.env("GIT_TERMINAL_PROMPT", "0");
    let output = command.args(args).output().expect("running git");
    assert!(
        output.status.success(),
        "`git {}` in {} failed: {}",
        args.join(" "),
        cwd.display(),
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8_lossy(&output.stdout).into_owned()
}

/// A git repository with a store-backed project and no hooks installed yet.
fn repository() -> (&'static TestEnv, Project<'static>) {
    let env = TestEnv::shared();
    let project = env.project().git().build();
    (env, project)
}

/// The receipt, read straight from the store.
fn receipt(store: &SqliteStore, project: ProjectId) -> Option<String> {
    store
        .read(|tx| tx.commit_scan_at(project))
        .expect("reading the commit-scan receipt")
}

/// Long enough that the next git commit lands in a later second than the
/// receipt.
///
/// Committer dates have one-second resolution and so does the receipt, so
/// "strictly after" needs a real second to have passed. A sleep is the honest
/// way to buy one: the alternative is stamping `GIT_COMMITTER_DATE` by hand,
/// which would make the fixture agree with the clock storyhook reads only by
/// coincidence.
fn wait_a_second() {
    std::thread::sleep(std::time::Duration::from_millis(1_100));
}

// ---------------------------------------------------------------------------
// The receipt is written by every `commit-sync`, whoever ran it
// ---------------------------------------------------------------------------

/// **Unconditional.** Not gated on commits found, links made, or stories
/// touched.
///
/// A project whose commits name no story is the ordinary case, not a corner
/// one, and a receipt that only advanced when a link happened would leave every
/// such project looking permanently unscanned — an advisory firing forever at a
/// user who has done nothing wrong. The whole feature's honesty rests on this
/// write being unconditional, so it is asserted against a repository where the
/// scan matches nothing at all.
#[test]
fn a_sync_that_matched_nothing_still_records_the_scan() {
    let (env, project) = repository();
    let store = project.open_store();
    let project_id = project.project_id(&store);

    git(
        env,
        project.path(),
        &["commit", "-q", "--allow-empty", "-m", "chore: nothing here"],
    );
    assert!(
        receipt(&store, project_id).is_none(),
        "fixture: nothing has scanned this project yet"
    );

    project.run(&["commit-sync"]).success();

    assert!(
        receipt(&store, project_id).is_some(),
        "a `commit-sync` that linked nothing still scanned the project, and the \
         receipt records the scan rather than its findings"
    );
}

/// The evidence the whole design turns on: **the managed hook's own sync leaves
/// the receipt behind**, with nobody typing anything.
///
/// This is the positive control for every silence assertion below. If a working
/// post-commit hook did not advance the receipt, "the receipt did not advance"
/// would mean nothing at all.
#[test]
fn the_managed_hooks_own_sync_records_the_scan() {
    let (env, project) = repository();
    let store = project.open_store();
    let project_id = project.project_id(&store);
    project.run(&["hooks", "install"]).success();

    // A baseline taken by hand rather than by install's arming, so this control
    // measures the hook alone.
    project.run(&["commit-sync"]).success();
    let before = receipt(&store, project_id).expect("the baseline scan is recorded");
    wait_a_second();
    git(
        env,
        project.path(),
        &["commit", "-q", "--allow-empty", "-m", "feat: real work"],
    );

    let after = receipt(&store, project_id).expect("the receipt survives");
    assert!(
        after > before,
        "the post-commit hook runs `story commit-sync`, so a commit made with \
         hooks live must advance the receipt on its own ({before} -> {after})"
    );
}

/// The receipt is the *latest* scan, not a log of scans.
#[test]
fn a_later_sync_replaces_the_earlier_receipt() {
    let (_env, project) = repository();
    let store = project.open_store();
    let project_id = project.project_id(&store);

    project.run(&["commit-sync"]).success();
    let first = receipt(&store, project_id).expect("the first scan is recorded");

    wait_a_second();
    project.run(&["commit-sync"]).success();
    let second = receipt(&store, project_id).expect("the second scan is recorded");

    assert!(second > first, "{second} must be later than {first}");
}
