//! Regression tests for the `.semver` release hooks.
//!
//! Guards the invariant that a `/semver bump` produces an *atomic, clean*
//! release commit: the pre-bump `sync-cargo-toml.sh` hook must edit **and stage**
//! both `Cargo.toml` and `Cargo.lock` before the plugin creates the pathspec-less
//! release commit. A post-bump edit (the old behavior) left them dirty afterward.

use std::fs;
use std::process::Command;

use storyhook_test_support::scratch_dir;

/// Run a command, asserting it succeeded, and return its stdout.
fn run(cmd: &mut Command) -> String {
    let out = cmd.output().expect("failed to spawn command");
    assert!(
        out.status.success(),
        "command {cmd:?} failed:\n--- stdout ---\n{}\n--- stderr ---\n{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr),
    );
    String::from_utf8_lossy(&out.stdout).into_owned()
}

#[test]
fn pre_bump_hook_syncs_and_stages_cargo_toml_and_lock() {
    let dir = scratch_dir();
    let p = dir.path();

    // A throwaway git repo standing in for a Rust project mid-bump.
    run(Command::new("git").args(["init", "-q"]).current_dir(p));
    run(Command::new("git")
        .args(["config", "user.email", "t@example.com"])
        .current_dir(p));
    run(Command::new("git")
        .args(["config", "user.name", "Test"])
        .current_dir(p));

    fs::write(
        p.join("Cargo.toml"),
        "[package]\nname = \"demo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    // Two packages + the lockfile format header, to prove the hook touches only
    // this package's version and leaves everything else byte-for-byte alone.
    fs::write(
        p.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n\
         version = 4\n\n\
         [[package]]\nname = \"other\"\nversion = \"1.0.0\"\n\n\
         [[package]]\nname = \"demo\"\nversion = \"0.1.0\"\ndependencies = [\n \"other\",\n]\n",
    )
    .unwrap();

    run(Command::new("git").args(["add", "-A"]).current_dir(p));
    run(Command::new("git")
        .args(["-c", "core.hooksPath=/dev/null", "commit", "-qm", "init"])
        .current_dir(p));

    // Invoke the *actual* repo hook the way the semver runner does: cwd = project
    // root, $NEW_VERSION carries the "v" prefix.
    let hook = format!(
        "{}/.semver/hooks/pre-bump/sync-cargo-toml.sh",
        env!("CARGO_MANIFEST_DIR")
    );
    run(Command::new("bash")
        .arg(&hook)
        .current_dir(p)
        .env("NEW_VERSION", "v0.2.0"));

    // Cargo.toml [package] version synced.
    let toml = fs::read_to_string(p.join("Cargo.toml")).unwrap();
    assert!(
        toml.contains("version = \"0.2.0\""),
        "Cargo.toml [package] version not synced:\n{toml}"
    );

    // Cargo.lock: this package synced; sibling package and lockfile header untouched.
    let lock = fs::read_to_string(p.join("Cargo.lock")).unwrap();
    assert!(
        lock.contains("name = \"demo\"\nversion = \"0.2.0\""),
        "demo package version not synced in Cargo.lock:\n{lock}"
    );
    assert!(
        lock.contains("name = \"other\"\nversion = \"1.0.0\""),
        "sibling package version must be left untouched:\n{lock}"
    );
    assert!(
        lock.contains("\nversion = 4\n"),
        "lockfile format version must survive:\n{lock}"
    );

    // Both files must be STAGED — the entire point of pre-bump + `git add`, so the
    // plugin's pathspec-less release commit picks them up.
    let staged = run(Command::new("git")
        .args(["diff", "--cached", "--name-only"])
        .current_dir(p));
    assert!(
        staged.lines().any(|l| l == "Cargo.toml"),
        "Cargo.toml must be staged; staged files:\n{staged}"
    );
    assert!(
        staged.lines().any(|l| l == "Cargo.lock"),
        "Cargo.lock must be staged; staged files:\n{staged}"
    );
}
