-- storyhook legacy archive database schema
--
-- Generated by scripts/capture-baseline.sh — do not hand-edit.
-- Captured: host `Psamathe` (Apple M1 Max, 10 cores) · Darwin 26.5.2/arm64 · rustc 1.97.1 (8bab26f4f 2026-07-14) (Homebrew) · commit `4179f48` (clean) · 2026-07-28T15:49:31Z
--
-- THIS IS SCHEMA VERSION 0.
--
-- `PRAGMA user_version` is 0 because nothing has ever set it: the legacy
-- archive is created by CREATE TABLE IF NOT EXISTS with no migration
-- framework behind it, and the one column added since (`deleted_reason`)
-- arrived via an unversioned ALTER. W1 introduces real migrations, and
-- every archive database already on every developer machine will present
-- itself as user_version 0 — so 0 must be defined to mean exactly the
-- schema below, including that late-added column.
--
-- PRAGMA user_version   = 0
-- PRAGMA schema_version = 2   (sqlite internal; bumps on every DDL)
-- PRAGMA journal_mode   = wal
-- capture tool: sqlite3 3.51.0

CREATE TABLE closed_stories (
            id TEXT PRIMARY KEY,
            snapshot_json TEXT NOT NULL,
            events_json TEXT NOT NULL,
            closed_at TEXT NOT NULL,
            state TEXT NOT NULL
        , deleted_reason TEXT);

-- Row counts at capture time:
--   closed_stories = 44 rows
