#!/usr/bin/env bash
#
# The browser harness's provider doubles -- the `claude`, `codex` and `tmux`
# executables a real daemon resolves on `PATH` during a Playwright run -- in
# one sourced library, so the daemon-shaped environment they must work in can
# be proven by a test rather than assumed by the runner (SH-626).
#
# WHY THE tmux DOUBLE BRIDGES ITS OWN KNOBS. Every tmux the daemon runs, it
# runs with a cleared, allowlisted environment (`src/env/spawn_env.rs`,
# `apply_dispatch_allowlist`): `PATH`, `HOME`, the XDG homes, `TMPDIR`, the
# locale/terminal names, and any `STORY_*`/`STORYHOOK_*` name -- and nothing
# called `FAKE_TMUX_*`. `scripts/run-e2e.sh` has bridged those knobs across
# that boundary since SH-263, but only for the dispatch child, through the
# generated dispatch wrapper. The daemon crosses the same boundary a second
# time on its own: the Full Auto reconciler's liveness probe
# (`ShellDispatcher::probe_window`, `tmux display-message -p -t <pane> ...`)
# and its `kill-window` never go through story.sh at all. Until SH-626 that
# probe reached a `tmux` double whose `set -u` died on an unset
# `FAKE_TMUX_IMPLEMENTATION`, exit 1, which the engine read as "the window is
# gone" -- deterministically, on every run, one change-poll interval after
# dispatch returned. The browser suite stayed green only when its stop-now
# beat that pass; under load it lost one run in five (SH-626, SH-575's
# residue). The knobs the dispatch wrapper re-exports are snapshotted one
# file per knob under a directory the runner names; the tmux double below is
# handed THAT directory, as data, and exports every knob it finds there that
# its own environment lacks before exec'ing the real fake. Both bridges read
# one snapshot, so a knob added later crosses both boundaries for free.
#
# The allowlist itself is a security boundary and is deliberately not
# widened for a fixture (SH-263's unanimous council verdict); the harness
# bridges on its own side, here.
#
# Deliberately no top-level `set` here: this file is sourced by a caller that
# has already chosen its own shell options (e2e-selection.sh's own rule). The
# generated scripts choose theirs individually.

# Writes the three doubles into PROVIDER_BIN, executable, and prints nothing.
#
#   write_e2e_provider_doubles PROVIDER_BIN KNOB_DIR FAKE_TMUX
#
#   PROVIDER_BIN  the directory to create the doubles in (created if absent)
#   KNOB_DIR      where the runner snapshots `FAKE_TMUX_*`, one file per knob;
#                 need not exist yet -- it is read when tmux runs, not now
#   FAKE_TMUX     the real fake tmux implementation the double execs
#
# Both paths are baked into the tmux double with `printf %q` -- as data, never
# interpolated into the script body -- so the double needs NO environment
# beyond `PATH` to find its fake and its knobs, which is exactly what the
# daemon's allowlist leaves it. Returns 1 with a message on any write failure.
write_e2e_provider_doubles() {
    local provider_bin="$1" knob_dir="$2" fake_tmux="$3"
    if [ -z "$provider_bin" ] || [ -z "$knob_dir" ] || [ -z "$fake_tmux" ]; then
        echo "write_e2e_provider_doubles: PROVIDER_BIN, KNOB_DIR and FAKE_TMUX are all required" >&2
        return 1
    fi
    if [ ! -f "$fake_tmux" ]; then
        echo "write_e2e_provider_doubles: fake tmux $fake_tmux does not exist" >&2
        return 1
    fi
    mkdir -p "$provider_bin" || return 1

    # SH-616: the daemon snapshots provider availability at startup, so both
    # supported executable names are supplied here instead of inheriting
    # whichever agent CLIs happen to be installed on the host. Claude stays
    # inert: the terminal double never executes its launch string.
    cat >"$provider_bin/claude" <<'PROVIDER' || return 1
#!/usr/bin/env bash
exit 0
PROVIDER

    # SH-584: the exact Codex launch string is executed at the terminal
    # boundary against this argv recorder. It writes into the fake tmux state
    # directory, which the tmux double has bridged by the time it runs this.
    cat >"$provider_bin/codex" <<'PROVIDER' || return 1
#!/usr/bin/env bash
set -euo pipefail
python3 -c 'import json, os, sys; json.dump({"argv": sys.argv[1:], "cwd": os.getcwd()}, sys.stdout)' "$@" >"$FAKE_TMUX_STATE/provider-argv.json"
PROVIDER

    {
        printf '#!/usr/bin/env bash\n'
        printf '# GENERATED by scripts/e2e-provider-doubles.sh -- regenerated every run, never committed.\n'
        printf 'set -euo pipefail\n'
        printf '_e2e_knob_dir=%q\n' "$knob_dir"
        printf '_e2e_fake_tmux=%q\n' "$fake_tmux"
        cat <<'TERMINAL'
# Bridge the runner's FAKE_TMUX_* snapshot into an environment that arrived
# without it (the daemon's own allowlisted tmux calls, SH-626). A knob the
# caller already carries wins, so the dispatch child's bridged environment
# and this one agree rather than compete.
for _f in "$_e2e_knob_dir"/FAKE_TMUX_*; do
  [ -f "$_f" ] || continue
  _name="${_f##*/}"
  if [ -z "${!_name+set}" ]; then
    export "$_name=$(cat "$_f")"
  fi
done
unset _f _name
if [ "${1:-}" = new-window ]; then
  previous=""
  launch=""
  pane_cwd=""
  for argument in "$@"; do
    if [ "$argument" = ';' ]; then launch="$previous"; break; fi
    if [ "$previous" = -c ]; then pane_cwd="$argument"; fi
    previous="$argument"
  done
  case "$launch" in
    codex\ *)
      [ -n "$pane_cwd" ] || { echo 'Codex fixture launch has no cwd' >&2; exit 64; }
      (cd "$pane_cwd" && bash -c "$launch")
      ;;
  esac
fi
exec "$_e2e_fake_tmux" "$@"
TERMINAL
    } >"$provider_bin/tmux" || return 1

    chmod 700 "$provider_bin/claude" "$provider_bin/codex" "$provider_bin/tmux" || return 1
}
