#![recursion_limit = "256"]

pub mod app;
pub mod cli;
pub mod decompose;
pub mod domain;
pub mod error;
pub mod event_hooks;
#[cfg(feature = "github-sync")]
pub mod github;
pub mod help_topics;
pub mod hooks;
pub mod lock;
pub mod mcp;
pub mod mcp_install;
pub mod output;
pub mod plugin;
pub mod storage;
pub mod tui;
