#![recursion_limit = "256"]

pub mod api;
pub mod block_notice;
pub mod cli;
pub mod clipboard;
pub mod daemon;
pub mod decompose;
pub mod domain;
pub mod env;
pub mod error;
pub mod event_hooks;
#[cfg(feature = "github-sync")]
pub mod github;
pub mod help_topics;
pub mod hooks;
pub mod invoke;
pub mod legacy;
pub mod mcp;
pub mod output;
pub mod plugin;
pub mod priority_notice;
pub mod service;
pub mod storage;
pub mod store;
pub mod token;
pub mod tui;
#[cfg(feature = "github-sync")]
pub mod update;
pub mod web;
