#![recursion_limit = "256"]

pub mod app;
pub mod cli;
pub mod decompose;
pub mod domain;
pub mod error;
pub mod event_hooks;
#[cfg(feature = "github-sync")]
pub mod github;
pub mod help_topics;
pub mod hooks;
pub mod invoke;
pub mod lock;
pub mod output;
pub mod plugin;
pub mod registry;
pub mod storage;
pub mod tui;
#[cfg(feature = "github-sync")]
pub mod update;
pub mod web;
